import { AppBar, Box, Container, IconButton, Toolbar, Typography } from "@mui/material";
import ExitToAppIcon from '@mui/icons-material/ExitToApp';
import { WebSocketManager } from "@/utils/WebSocketManager";
import { useEffect } from "react";
import MainPanel from "@/components/MainPanel";

export default async function Home() {
    
    
    return (
        <Box sx={{ flexGrow: 1 }}>
            <AppBar position="static" sx={{ mb: 6 }}>
                <Toolbar>
                    <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                        {"serverStatePanel"}
                    </Typography>
                    </Toolbar>
            </AppBar>
            <MainPanel></MainPanel>
            <Container sx={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center"
            }}>
                <Typography component="p">
                    Home page to project generated by Developers Suite Code Generator.
                </Typography>
            </Container>
        </Box >
    );
}